name: temperature12k
channels:
    - conda-forge
dependencies:
    - python=3.7
    - r-kohonen
    - pygam
    - xarray
    - distributed
    - dask
    - scikit-learn
    - psyplot
    - psy-maps
    - rpy2
    - pandas
    - pyqt  # necessary for lipd...
    - pip
    - pytest
    - pytest-sugar
    - pytest-html
    - jupyter
    - notebook
    - xlsxwriter
    - xlrd
    - openpyxl
    - geopandas
    - seaborn
    - pip:
        - lipd
        - latlon-utils
